export const ADMIN_ACTION_TYPES = {
  USER_CREATED: 'USER_CREATED',
  USER_ROLES_CHANGED: 'USER_ROLES_CHANGED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
  PASSWORD_RESET_TRIGGERED: 'PASSWORD_RESET_TRIGGERED',
  USER_EMAIL_UPDATED: 'USER_EMAIL_UPDATED', // Reserved
};
